title: Bramble Beard
email: hi@dereknutile.com
description: Web application to securely store and share secret information.
tagline: Securely shove your secrets in the brambly beard.
baseurl: ""
favicon: "/assets/ico/favicon.png"
url: "http://bramblebeard.github.io/"
sourceUrl: "https://github.com/BrambleBeard/app"
facebook-username: "dereknutile"
twitter-username: "dereknutile"
google-plus-username: "+dereknutile"
google-analytics: "UA-CODE-GOES-HERE"
