title: BrambleBeard
email: hi@dereknutile.com
description: Securely shove your secrets in the brambly beard.
tagline: "The Mock-up Machine"
baseurl: "" # the subpath of your site, e.g. /blog
favicon: "/assets/ico/favicon.png"
url: "http://bramblebeard.github.io/"
facebook-username: "dereknutile"
twitter-username: "dereknutile"
gootgle-plus-username: "+dereknutile"
google-analytics: "UA-CODE-GOES-HERE"
