# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BrambleBeard
email: hi@dereknutile.com
description: Securely shove your secrets in the brambly beard.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bramblebeard.github.io/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
