title: Bramble Beard
email: hi@dereknutile.com
description: Web application to store secret information securely.
tagline: Securely shove your secrets in the brambly beard.
baseurl: "" # the subpath of your site, e.g. /blog
favicon: "/assets/ico/favicon.png"
url: "http://bramblebeard.github.io/"
facebook-username: "dereknutile"
twitter-username: "dereknutile"
gootgle-plus-username: "+dereknutile"
google-analytics: "UA-CODE-GOES-HERE"
